defaults: &defaults
  base: 'https://api.stagingeb.com/v1/'
  properties: 'https://api.stagingeb.com/v1/properties'
  contact: 'https://api.stagingeb.com/v1/contact_requests'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults